### PR TITLE
Be more forgiving in log processing

### PR DESCRIPTION
**Pull request by AndreasAntener**
Hey @DrTon 
We had some logging issues lately on PX4 and it would be awesome if Flightplot doesn't react so bad on corrupt logs :).. I updated jMAVlib to be more forgiving on errors and improved performance a lot for processing corrupt PX4 logs.

API for error reporting on LogReader is just a very basic suggestion. If you have any other ideas there, let me know.

(the performance issue was throwing and catching exceptions on bad header)

### CODE REVIEW

**Comment by DrTon** [comment]
I'm not sure if it's good approach. Too many errors may result huge output on console and memory consumption, while user may still see something on plots. On one hand we need to fix logging instead, on another it may be useful e.g. for mavlink logs, received via unstable radio link. What about saving first 10 errors max? The rest looks good for me except I would save not string but Exception objects so in console user, no, developer :) can see traceback.

**Comment by DrTon** [comment]
BTW can you send me any corrupt PX4 log for experiments?

**Comment by AndreasAntener** [comment]
Here's one: http://logs.uaventure.com/logmuncher/charts/dXby9diEtJ27zkJgidsiKa/raw_flight_log.px4log

**Comment by AndreasAntener** [comment]
Ok, I think it make sense to have the stack trace since, as you said, this is mearly for devs not for users. So I can change it to just remember if there was an error and do printStackTrace directly instead of buffering the messages.

**Comment by AndreasAntener** [comment]
@DrTon this is now updated. I think this goes into the right direction for making the user aware of non-blocking errors with the log. Btw, in those cases there is never a stack trace involved since they aren't actually exception.

**Comment by DrTon** [comment]
Merged to master after some rework, thanks!

**Pull request merged**
